import OpenAI from "openai";

interface RisksRequest {
  sector: string;
  description: string;
  occupations: string;
}

class GetRisksService {
  async execute({ sector, description, occupations }: RisksRequest) {
    if (!sector || !occupations || !description) {
      throw new Error(
        "Preencha o setor, descrição e e funções para buscar mais detalhes",
      );
    }
    const client = new OpenAI();

    const response = await client.responses.create({
      model: "gpt-4.1",
      input: `Você é um assistente que retorna informações sobre riscos no setor ${sector}, ${description ? `descrito: ${description}` : ""}, nesse setor tem as seguintes funções de trabalho: ${occupations}. de acordo com as funções no Brasil.
 [
  { "agente": "Vibrações de Mãos e Braços- AREN", "tipo": "Físico" },
  { "agente": "Radiações Ionizantes", "tipo": "Físico" },
  { "agente": "Radiação infravermelho", "tipo": "Físico" },
  { "agente": "Frio", "tipo": "Físico" },
  { "agente": "Calor", "tipo": "Físico" },
  { "agente": "Poeiras totais/Respiráveis", "tipo": "Químico" },
  { "agente": "Fumos metálicos (Mn e seus compostos)", "tipo": "Químico" },
  { "agente": "Trabalho com animais infectados", "tipo": "Biológico" },
  { "agente": "Doenças Infecto-contagiosas", "tipo": "Biológico" },
  { "agente": "Movimentos Repetitivo", "tipo": "Ergonômico" },
  { "agente": "Levantamento, transporte manual de pesos", "tipo": "Ergonômico" },
  { "agente": "Postura incômoda por longos períodos", "tipo": "Ergonômico" },
  { "agente": "Ritmo Excessivo", "tipo": "Ergonômico" },
  { "agente": "Arranjo físico inadequado", "tipo": "Acidentes" },
  { "agente": "Máquinas e equipamentos", "tipo": "Acidentes" },
  { "agente": "Choque elétrico", "tipo": "Acidentes" },
  { "agente": "Etanol, gasolina, benzeno", "tipo": "Químico" },
  { "agente": "Hidrocarbonetos", "tipo": "Químico" },
  { "agente": "Sílica livre cristalizada - poeira respirável", "tipo": "Químico" },
  { "agente": "Álcalis Cáusticos", "tipo": "Químico" },
  { "agente": "Objeto cortantes", "tipo": "Acidentes" },
  { "agente": "Trabalho em altura (maior que 2 metros)", "tipo": "Acidentes" },
  { "agente": "Picadas Animais Peçonhentos", "tipo": "Acidentes" },
  { "agente": "Luminosidade", "tipo": "Ergonômico" },
  { "agente": "Engolfamento", "tipo": "Acidentes" },
  { "agente": "Pressão Hiperbárica", "tipo": "Físico" },
  { "agente": "Ruído Contínuo ou Intermitente", "tipo": "Físico" },
  { "agente": "Incêndio/explosão", "tipo": "Acidentes" },
  { "agente": "Queda de objetos", "tipo": "Acidentes" },
  { "agente": "Queimadura", "tipo": "Acidentes" },
  { "agente": "Pressão Hipobárica", "tipo": "Físico" },
  { "agente": "Ausência de Fator de Risco", "tipo": "Não Especificado" },
  { "agente": "Calor acima LT", "tipo": "Físico" },
  { "agente": "Vibrações de corpo inteiro - (AREN e VDVR)", "tipo": "Físico" },
  { "agente": "Ruído contínuo ou intermitente (Leg. Prev.)", "tipo": "Físico" },
  { "agente": "Acetileno", "tipo": "Químico" },
  { "agente": "Tolueno e Xileno, Etanol", "tipo": "Químico" },
  { "agente": "Hidrocarbonetos Aromáticos", "tipo": "Químico" },
  { "agente": "Poeira Ambiente ou respirável", "tipo": "Químico" },
  { "agente": "Óleo Mineral", "tipo": "Químico" },
  { "agente": "Óleo Mineral, Graxa", "tipo": "Químico" },
  { "agente": "Poeira sílica", "tipo": "Químico" },
  { "agente": "Cádmio e seus Compostos", "tipo": "Químico" },
  { "agente": "Chumbo e seus Compostos", "tipo": "Químico" },
  { "agente": "Cobre e seus Compostos", "tipo": "Químico" },
  { "agente": "Cromo e seus Compostos", "tipo": "Químico" },
  { "agente": "Poeira de cimento", "tipo": "Químico" },
  { "agente": "Fósforo e seus Compostos", "tipo": "Químico" },
  { "agente": "Radiação não ionizante UVA UVB", "tipo": "Físico" },
  { "agente": "Condições Adversas", "tipo": "Acidentes" },
  { "agente": "Umidade", "tipo": "Físico" },
  { "agente": "Gases e vapores", "tipo": "Químico" },
  { "agente": "Postura sentada por longos períodos", "tipo": "Ergonômico" },
  { "agente": "Bactérias, Vírus", "tipo": "Biológico" },
  { "agente": "Mobiliário sem meios de regulagem de ajuste", "tipo": "Ergonômico" },
  { "agente": "Diminuição da sua capacidade visual", "tipo": "Ergonômico" },
  { "agente": "Trabalho em ambientes com risco de queda do mesmo nível/ Nível diferente", "tipo": "Acidentes" },
  { "agente": "Batidas contra, colisões, atropelamentos", "tipo": "Acidentes" },
  { "agente": "Condução de veículos de qualquer natureza (Trânsito)", "tipo": "Acidentes" },
  { "agente": "Uso frequente de pedais e alavancas", "tipo": "Ergonômico" },
  { "agente": "Uso frequente de alavancas e pedais", "tipo": "Ergonômico" },
  { "agente": "Frequente deslocamento a pé durante a jornada de trabalho", "tipo": "Ergonômico" },
  { "agente": "Piso irregular", "tipo": "Acidentes" },
  { "agente": "Projeção de Partículas nos Olhos", "tipo": "Acidentes" },
  { "agente": "Exigência de concentração e atenção.", "tipo": "Ergonômico" },
  { "agente": "Mobiliário ou equipamento sem espaço para movimentação de segmentos corporais", "tipo": "Ergonômico" },
  { "agente": "Pisos, passagens, passarelas, escadas, plataformas, rampas, quinas vivas", "tipo": "Acidentes" },
  { "agente": "Objetos cortantes e/ou perfurocortantes", "tipo": "Acidentes" },
  { "agente": "Graxa ou lubrificante", "tipo": "Químico" },
  { "agente": "Manganês e seus compostos", "tipo": "Químico" },
  { "agente": "Ferro, óxido (Fe2O3)", "tipo": "Químico" },
  { "agente": "Níquel e seus compostos tóxicos (inclui níquel carbonila e níquel tetracarbonila)", "tipo": "Químico" },
  { "agente": "Ferramentas manuais", "tipo": "Acidentes" },
  { "agente": "Gasolina (Benzeno, Tolueno, Xileno)", "tipo": "Químico" },
  { "agente": "Cimento e partículas suspensas", "tipo": "Químico" },
  { "agente": "Óleo mineral, excluídos os fluídos de trabalho com metais", "tipo": "Químico" },
  { "agente": "Bactérias, vírus, protozoários, fungos, príons, parasitas e outros", "tipo": "Biológico" },
  { "agente": "Espaço Confinado", "tipo": "Acidentes" },
  { "agente": "Ácido Linear Alquilbenzeno Sulfônico", "tipo": "Químico" },
  { "agente": "Clorodifluormetano", "tipo": "Químico" },
  { "agente": "Hidróxido de sódio", "tipo": "Químico" },
  { "agente": "Cloro", "tipo": "Químico" },
  { "agente": "Vírus e Bactérias", "tipo": "Biológico" },
  { "agente": "Solventes", "tipo": "Químico" },
  { "agente": "Querosene, Thinners", "tipo": "Químico" },
  { "agente": "Ataque de animais (peçonhentos, selvagens, insetos etc.)", "tipo": "Acidentes" },
  { "agente": "Acidentes Mecânicos", "tipo": "Acidentes" },
  { "agente": "Batida contra, colisão, atropelamento", "tipo": "Acidentes" },
  { "agente": "Contato com - Partes ou móveis rotativas de Estruturas, Estruturas, Máquinas ou equipamentos", "tipo": "Acidentes" },
  { "agente": "Prensamento do corpo ou partes do corpo", "tipo": "Acidentes" },
  { "agente": "Contato/exposição a produtos químicos", "tipo": "Acidentes" },
  { "agente": "Ausência de Fator de Risco / Agente Nocivo", "tipo": "Não Especificado" },
  { "agente": "Colisão ou Abalroamento", "tipo": "Acidentes" },
  { "agente": "CAP", "tipo": "Químico" },
  { "agente": "Soda caustica , ácido clorídrico , hidróxido de amônia", "tipo": "Químico" },
  { "agente": "Detergente Enzimático", "tipo": "Químico" },
  { "agente": "Não existente (Ausencia de Fator de Risco)", "tipo": "Físico" },
  { "agente": "Inalação de Fumaça e Particulados", "tipo": "Químico" },
  { "agente": "Não existe (Ausencia de Fator de Risco)", "tipo": "Químico" },
  { "agente": "Contato com materiais contaminados", "tipo": "Biológico" },
  { "agente": "Microrganismos Vivos", "tipo": "Biológico" },
  { "agente": "Desengraxante em geral", "tipo": "Químico" },
  { "agente": "Afogamento", "tipo": "Acidentes" },
  { "agente": "Trabalho a quente", "tipo": "Acidentes" },
  { "agente": "Talco - ( Mg3(Si2O5)2(OH)2 ou 3MgO.4SiO2.H2O )", "tipo": "Químico" },
  { "agente": "Cimento, argamassa ou cal", "tipo": "Químico" },
  { "agente": "Tintas, esmaltes, vernizes e outras variados", "tipo": "Químico" },
  { "agente": "Formol (Formaldeído)", "tipo": "Químico" },
  { "agente": "Sabão isolante de tubulações", "tipo": "Químico" },
  { "agente": "Mercúrio (Hg) e seus Compostos", "tipo": "Químico" },
  { "agente": "Corante Fluorescente/Sodium C10-16 alkyl sulfate", "tipo": "Químico" },
  { "agente": "Celulose", "tipo": "Químico" },
  { "agente": "Ácido cítrico, Bifluoreto de amônio, Carbonato de Sódio, Nitrito de Sódio, Soda Caustica", "tipo": "Químico" },
  { "agente": "Particulados", "tipo": "Químico" },
  { "agente": "Ozónio", "tipo": "Químico" },
  { "agente": "Respingos de produtos químicos", "tipo": "Acidentes" },
  { "agente": "Clorexidina aquosa ou Clorexidina alcoólica", "tipo": "Químico" },
  { "agente": "Hipoclorito de sódio", "tipo": "Químico" },
  { "agente": "Trabalho em altura - 1,80 m", "tipo": "Acidentes" },
  { "agente": "Amônia", "tipo": "Químico" },
  { "agente": "Enxofre", "tipo": "Químico" },
  { "agente": "Silicone", "tipo": "Químico" },
  { "agente": "dióxido de enxofre", "tipo": "Químico" },
  { "agente": "Cortes e lacerações", "tipo": "Acidentes" },
  { "agente": "Verniz, solvente, tinta outros derivados", "tipo": "Químico" },
  { "agente": "Manuseio de materiais de limpeza em geral.", "tipo": "Químico" },
  { "agente": "Produtos Domissanitários", "tipo": "Químico" },
  { "agente": "Quedas de mesmo nível e desnível", "tipo": "Acidentes" },
  { "agente": "Acidentes - Mordidas e/ou arranhões causadas por animais domésticos.", "tipo": "Acidentes" },
  { "agente": "Q- Herbicida, fungicidas, inseticidas", "tipo": "Químico" },
  { "agente": "Manuseio ou transporte de inflamáveis", "tipo": "Acidentes" },
  { "agente": "Aerodispersoides (névoas, neblinas, fumos e poeiras)", "tipo": "Químico" },
  { "agente": "Cola, cola PVC, cola adesivo de contato", "tipo": "Químico" },
  { "agente": "Zinco", "tipo": "Químico" },
  { "agente": "Princípio ativo 2.4D picloram, Tricopir ,Fluroxipir ,herbicidas, acefato, Acetamiprid", "tipo": "Químico" },
  { "agente": "Quedas e tropeços", "tipo": "Acidentes" },
  { "agente": "Produtos de limpeza alcalinos", "tipo": "Químico" },
  { "agente": "Fluidos Refrigerantes", "tipo": "Químico" },
  { "agente": "Etil benzeno", "tipo": "Químico" },
  { "agente": "Acetato de etila", "tipo": "Químico" },
  { "agente": "Ácido benzoico", "tipo": "Químico" },
  { "agente": "Ácido bórico", "tipo": "Químico" },
  { "agente": "Cafeína", "tipo": "Químico" },
  { "agente": "Diltiazem", "tipo": "Químico" },
  { "agente": "Óleo lubrificante", "tipo": "Químico" },
  { "agente": "Hidroxizina", "tipo": "Químico" },
  { "agente": "Lidocaína", "tipo": "Químico" },
  { "agente": "Manitol", "tipo": "Químico" },
  { "agente": "Paracetamol", "tipo": "Químico" },
  { "agente": "Tetracaína/Lidocaína", "tipo": "Químico" },
  { "agente": "Maquinas manuais", "tipo": "Acidentes" },
  { "agente": "Desconforto térmico", "tipo": "Ergonômico" },
  { "agente": "Baixa umidade do ar", "tipo": "Físico" },
  { "agente": "Baixa umidade", "tipo": "Físico" },
  { "agente": "Ataque de animais ou insetos", "tipo": "Acidentes" },
  { "agente": "Trabalho diurno ou noturno", "tipo": "Ergonômico" },
  { "agente": "Exposição a Produtos Químicos", "tipo": "Químico" },
  { "agente": "Álcool 70%", "tipo": "Químico" },
  { "agente": "Formol", "tipo": "Químico" },
  { "agente": "Glutaraldeído", "tipo": "Químico" },
  { "agente": "Benzeno", "tipo": "Químico" },
  { "agente": "Iodo", "tipo": "Químico" },
  { "agente": "Limpa contato Elétrico ( hidrofluorcarbono)", "tipo": "Químico" },
  { "agente": "Gesso", "tipo": "Químico" },
  { "agente": "Hormônio citostático e Antibiótico", "tipo": "Químico" },
  { "agente": "Produtos Biodegradáveis", "tipo": "Químico" },
  { "agente": "Lixos e dejetos orgânicos", "tipo": "Biológico" },
  { "agente": "Alérgenos", "tipo": "Químico" },
  { "agente": "Fertilizante", "tipo": "Químico" },
  { "agente": "Impermeabilizantes", "tipo": "Químico" },
  { "agente": "Gás R22, R410 e R32", "tipo": "Químico" },
  { "agente": "Exposição à Tela", "tipo": "Ergonômico" },
  { "agente": "Mobiliário e/ou superfícies com quinas vivas, rebarbas ou elementos de fixação expostos", "tipo": "Acidentes" },
  { "agente": "Adesivo plástico PVC", "tipo": "Químico" },
  { "agente": "Diesel", "tipo": "Químico" },
  { "agente": "Esmagamento/ Prensamento", "tipo": "Acidentes" },
  { "agente": "Sulfato de cálcio", "tipo": "Químico" },
  { "agente": "Desconforto ou cansaço visual", "tipo": "Ergonômico" },
  { "agente": "Esforço Físico", "tipo": "Ergonômico" },
  { "agente": "Projeção de partículas", "tipo": "Acidentes" },
  { "agente": "Imprudência na direção", "tipo": "Acidentes" },
  { "agente": "Queda de rocha", "tipo": "Acidentes" },
  { "agente": "Veículos pesados", "tipo": "Acidentes" },
  { "agente": "Transporte de produtos inflamáveis", "tipo": "Acidentes" },
  { "agente": "Resíduos classe I inflamabilidade, corrosividade, reatividade, toxidade ou patogenicidade", "tipo": "Químico" },
  { "agente": "Resíduos Classe II não-inertes ou inertes", "tipo": "Químico" },
  { "agente": "Resina", "tipo": "Químico" },
  { "agente": "Monóxido de carbono", "tipo": "Químico" },
  { "agente": "Aberturas no piso, Saliencias, Descontinuidades, obstruções ou escorregadio", "tipo": "Acidentes" },
  { "agente": "Jornada de trabalho prolongada", "tipo": "Ergonômico" },
  { "agente": "Intempéries sol ou chuva", "tipo": "Acidentes" },
  { "agente": "Vibração de corpo inteiro", "tipo": "Físico" },
  { "agente": "Deslizamento do talude", "tipo": "Acidentes" },
  { "agente": "Monotonia", "tipo": "Ergonômico" },
  { "agente": "Álcool Etílico Etanol", "tipo": "Químico" },
  { "agente": "Metil Etil cetona, BTX", "tipo": "Químico" },
  { "agente": "Fogos de artifício", "tipo": "Acidentes" },
  { "agente": "Tombamento de máquinas ou equipamentos", "tipo": "Acidentes" },
  { "agente": "Produto INTERCAP", "tipo": "Químico" },
  { "agente": "Nafta", "tipo": "Químico" },
  { "agente": "Gás natural", "tipo": "Químico" },
  { "agente": "Acidente com arma de fogo", "tipo": "Acidentes" },
  { "agente": "Situações de estresse", "tipo": "Ergonômico" },
  { "agente": "2,4 D + PICLORAM", "tipo": "Químico" },
  { "agente": "Fixador para hidrossemeadura", "tipo": "Químico" },
  { "agente": "Fibra de madeira para hidrossemeadura", "tipo": "Químico" },
  { "agente": "Risco de violência física", "tipo": "Acidentes" },
  { "agente": "Poeira Toxicas", "tipo": "Químico" },
  { "agente": "Radiação Ultravioleta", "tipo": "Físico" },
  { "agente": "Maquinas pesadas", "tipo": "Acidentes" },
  { "agente": "Acidentes de trânsito", "tipo": "Acidentes" },
  { "agente": "Poeira Vegetal", "tipo": "Químico" },
  { "agente": "Desengraxante em geral (Limpeza automotiva)", "tipo": "Químico" },
  { "agente": "Cortes", "tipo": "Acidentes" },
  { "agente": "Assédio Moral/Sexual", "tipo": "Ergonômico" },
  { "agente": "Clima Organizacional", "tipo": "Ergonômico" },
  { "agente": "clorofórmio", "tipo": "Químico" },
  { "agente": "Ácido Nítrico", "tipo": "Químico" },
  { "agente": "Cloreto de Hidrogênio (Ácido Clorídrico)", "tipo": "Químico" },
  { "agente": "N-Hexano", "tipo": "Químico" },
  { "agente": "Hidróxido de Amônia", "tipo": "Químico" },
  { "agente": "Ácido Sulfúrico", "tipo": "Químico" },
  { "agente": "Falta de Autonomia e Controle sobre o Trabalho", "tipo": "Ergonômico" },
  { "agente": "Conflitos interpessoais", "tipo": "Ergonômico" },
  { "agente": "Ensaios químicos", "tipo": "Químico" },
  { "agente": "Falta de autonomia no trabalho para gestão de pausas", "tipo": "Ergonômico" },
  { "agente": "Baixa autonomia na organização do próprio trabalho", "tipo": "Ergonômico" },
  { "agente": "Insatisfação no trabalho por falta de feedback sobre desempenho", "tipo": "Ergonômico" },
  { "agente": "Falta de suporte social e aumento da sensação de sobrecarga", "tipo": "Ergonômico" },
  { "agente": "Insegurança e ansiedade devido à falta de clareza de funções", "tipo": "Ergonômico" },
  { "agente": "Vapores", "tipo": "Químico" },
  { "agente": "Insegurança e resistência às mudanças organizacionais", "tipo": "Ergonômico" },
  { "agente": "Fadiga ocupacional por falta de pausas", "tipo": "Ergonômico" },
  { "agente": "Comunicação hostil e risco de assédio moral", "tipo": "Ergonômico" },
  { "agente": "Desmotivação por falta de reconhecimento de ideias", "tipo": "Ergonômico" },
  { "agente": "Gazes tóxicos , fumaças", "tipo": "Químico" },
  { "agente": "glutaraldeído.", "tipo": "Químico" },
  { "agente": "Desorganização da jornada e impacto na conciliação trabalho vida pessoal.", "tipo": "Ergonômico" },
  { "agente": "Ambiente organizacional hostil e propenso a conflitos", "tipo": "Ergonômico" },
  { "agente": "Risco de desgaste emocional e desenvolvimento de transtornos mentais relacionados ao trabalho.", "tipo": "Ergonômico" },
  { "agente": "Isolamento emocional e agravamento de problemas no ambiente de trabalho.", "tipo": "Ergonômico" },
  { "agente": "Dificuldade de conciliação trabalho-vida pessoal por rigidez de jornada.", "tipo": "Ergonômico" },
  { "agente": "Imposição de ritmos de trabalho inadequados e sensação de desvalorização", "tipo": "Ergonômico" },
  { "agente": "Postura de pé por longos períodos", "tipo": "Ergonômico" },
  { "agente": "Exigência de alto nível de concentração, atenção e memória", "tipo": "Ergonômico" },
  { "agente": "Postura inadequada", "tipo": "Ergonômico" },
  { "agente": "Corte e/ou ferimentos e/ou esmagamentos e/ou escoriações", "tipo": "Acidentes" },
  { "agente": "Ruído contínuo ou intermitente (Leg. Trabalhista)", "tipo": "Físico" },
  { "agente": "Atropelamento", "tipo": "Acidentes" },
  { "agente": "Falta de participação e sensação de imposição de mudanças.", "tipo": "Ergonômico" },
  { "agente": "Agentes Biológicos", "tipo": "Biológico" },
  { "agente": "Sobrecarga de trabalho e assédio", "tipo": "Ergonômico" },
  { "agente": "Vapores orgânicos", "tipo": "Químico" },
  { "agente": "Projeção de água e objetos sob pressão", "tipo": "Acidentes" },
  { "agente": "Desrespeito e risco de conflitos interpessoais.", "tipo": "Ergonômico" },
  { "agente": "Isolamento social e falta de suporte no ambiente de trabalho.", "tipo": "Ergonômico" },
  { "agente": "Pólvora Negra (Carvão vegetal, Enxofre, Nitrato de potássio)", "tipo": "Químico" },
  { "agente": "Negro de fumo", "tipo": "Químico" },
  { "agente": "Restrição da criatividade e perda de engajamento no trabalho.", "tipo": "Ergonômico" },
  { "agente": "Impacto contra objetos", "tipo": "Acidentes" },
  { "agente": "Demandas emocionais intensas e exposição a situações de conflito", "tipo": "Ergonômico" },
  { "agente": "Desmotivação e perda de engajamento devido a mudanças mal geridas.", "tipo": "Ergonômico" },
  { "agente": "Engolfamento ou soterramento", "tipo": "Acidentes" },
  { "agente": "Contaminação de solos", "tipo": "Químico" },
  { "agente": "Contaminação de solos.", "tipo": "Químico" },
  { "agente": "Partes móveis", "tipo": "Acidentes" },
  { "agente": "Fadiga Visual", "tipo": "Ergonômico" },
  { "agente": "Hormônios e Antibióticos", "tipo": "Químico" },
  { "agente": "Poeira PNOS - Respiráveis", "tipo": "Químico" },
  { "agente": "Sobrecarga e comprometimento da produtividade", "tipo": "Ergonômico" },
  { "agente": "Contato com líquidos ou superfícies aquecidas", "tipo": "Acidentes" },
  { "agente": "Assédio moral e sofrimento psíquico", "tipo": "Ergonômico" },
  { "agente": "Acidente Automobilístico", "tipo": "Acidentes" },
  { "agente": "Óleos e Graxas", "tipo": "Químico" },
  { "agente": "Estresse ocupacional por metas inatingíveis", "tipo": "Ergonômico" },
  { "agente": "Fatores de Intempéries", "tipo": "Acidentes" },
  { "agente": "Arco elétrico em média tensão (250 V a 1.000 V)", "tipo": "Acidentes" },
  { "agente": "Demanda cognitiva", "tipo": "Ergonômico" },
  { "agente": "Presenteísmo", "tipo": "Ergonômico" },
  { "agente": "Demandas quantitativas", "tipo": "Ergonômico" },
  { "agente": "Butóxi etanol", "tipo": "Químico" },
  { "agente": "Baixa demanda no trabalho (subcarga)", "tipo": "Ergonômico" },
  { "agente": "Atingido por outros, queda de peças/estruturas/ferramentas/ferramentas, projeção de materiais (ferramentas, peças, fragmentos, fagulhas)", "tipo": "Acidentes" },
  { "agente": "Insegurança no emprego e ausência de perspectivas de crescimento profissional", "tipo": "Ergonômico" },
  { "agente": "Piretrinas e Piretróides (inseticidas)", "tipo": "Químico" },
  { "agente": "Urotropina", "tipo": "Químico" },
  { "agente": "Controle de Produtividade", "tipo": "Ergonômico" },
  { "agente": "Ácido Acético (ácido etanóico)", "tipo": "Químico" },
  { "agente": "Escadas e rampas inadequadas", "tipo": "Acidentes" },
  { "agente": "Ambiente de trabalho conflituoso e insatisfação coletiva", "tipo": "Ergonômico" },
  { "agente": "Exposição a agrotóxicos e produtos veterinários", "tipo": "Químico" },
  { "agente": "queda de nível e desnível", "tipo": "Acidentes" },
  { "agente": "Descarga atmosférica", "tipo": "Acidentes" },
  { "agente": "Impacto com equipamentos", "tipo": "Acidentes" },
  { "agente": "Exaustão física e mental por sobrecarga de trabalho", "tipo": "Ergonômico" },
  { "agente": "Insatisfação no trabalho por falta de feedback sobre desempenho.", "tipo": "Ergonômico" },
  { "agente": "Ferro", "tipo": "Químico" },
  { "agente": "Acetona", "tipo": "Químico" },
  { "agente": "Etanol", "tipo": "Químico" },
  { "agente": "Acetato de butila", "tipo": "Químico" },
  { "agente": "N-hexano.", "tipo": "Químico" },
  { "agente": "Tolueno", "tipo": "Químico" },
  { "agente": "Xileno", "tipo": "Químico" },
  { "agente": "Stoddard solvent", "tipo": "Químico" },
  { "agente": "Fenol", "tipo": "Químico" },
  { "agente": "Recompensa", "tipo": "Ergonômico" },
  { "agente": "Justiça e Respeito", "tipo": "Ergonômico" },
  { "agente": "Comunidade Social no Trabalho", "tipo": "Ergonômico" },
  { "agente": "Sobrecarga de trabalho e conflitos de prioridade", "tipo": "Ergonômico" },
  { "agente": "Falta de apoio emocional e segurança nas relações hierárquicas", "tipo": "Ergonômico" },
  { "agente": "Fumos de asfalto", "tipo": "Químico" },
  { "agente": "Desmotivação e queda de produtividade pela falta de reconhecimento da liderança", "tipo": "Ergonômico" },
  { "agente": "Queda com Diferente Nível, Queda do mesmo Nível, Queda de Ferramentas, Queda de Materiais", "tipo": "Acidentes" },
  { "agente": "Acidente", "tipo": "Acidentes" },
  { "agente": "Poeira de ferro", "tipo": "Químico" },
  { "agente": "Projeção de Materiais", "tipo": "Acidentes" },
  { "agente": "Poeiras de Madeiras", "tipo": "Químico" },
  { "agente": "Desmotivação por falta de visão dos objetivos organizacionais", "tipo": "Ergonômico" },
  { "agente": "Barreiras de comunicação e agravamento de conflitos no ambiente de trabalho", "tipo": "Ergonômico" },
  { "agente": "Iluminação inadequada", "tipo": "Ergonômico" },
  { "agente": "Contato com Superfícies Aquecidas", "tipo": "Acidentes" },
  { "agente": "Exposição a vapores tóxicos de defensivos agrícolas", "tipo": "Químico" },
  { "agente": "Derramamento de defensivos agrícolas", "tipo": "Acidentes" },
  { "agente": "Explosão de pneus durante enchimento", "tipo": "Acidentes" },
  { "agente": "Exposição a resíduos de defensivos agrícolas", "tipo": "Químico" },
  { "agente": "Incêndio", "tipo": "Acidentes" },
  { "agente": "Queda de carga", "tipo": "Acidentes" },
  { "agente": "Exposição a medicamentos e desinfetantes", "tipo": "Químico" },
  { "agente": "Pressão por produtividade e risco de erros operacionais", "tipo": "Ergonômico" },
  { "agente": "Manuseio de ferramentas pesadas", "tipo": "Acidentes" },
  { "agente": "Atividade sobre Equipamento pressurizado", "tipo": "Acidentes" },
  { "agente": "Içamento de cargas", "tipo": "Acidentes" },
  { "agente": "Riscos biológicos não codificados pelo eSocial", "tipo": "Biológico" },
  { "agente": "Movimentos repetitivos e excesso de peso nas atividade laborais", "tipo": "Ergonômico" },
  { "agente": "Fadiga e sonolência", "tipo": "Ergonômico" },
  { "agente": "Fadiga física e mental", "tipo": "Ergonômico" },
  { "agente": "Agressão física", "tipo": "Acidentes" },
  { "agente": "Contato com produtos cosméticos", "tipo": "Químico" },
  { "agente": "Escadas, rampas", "tipo": "Acidentes" },
  { "agente": "Exposição a agrotóxicos", "tipo": "Químico" },
  { "agente": "Risco de desgaste emocional", "tipo": "Ergonômico" },
  { "agente": "Peróxido de metil etil cetona", "tipo": "Químico" },
  { "agente": "Estireno", "tipo": "Químico" },
  { "agente": "Radiação não ionizante", "tipo": "Físico" },
  { "agente": "Cortes e Perfurações", "tipo": "Acidentes" },
  { "agente": "Equipamentos e Ferramentas", "tipo": "Acidentes" },
  { "agente": "Nevoas e vapores de gasolina e óleo diesel", "tipo": "Químico" },
  { "agente": "Sobrecarga física/muscular", "tipo": "Ergonômico" },
  { "agente": "Exposição a ureia automotiva e amônia", "tipo": "Químico" },
  { "agente": "Quedas", "tipo": "Acidentes" },
  { "agente": "Atropelamento, Colisão", "tipo": "Acidentes" },
  { "agente": "Arranjo Inadequado", "tipo": "Ergonômico" },
  { "agente": "Risco de fadiga extrema e queda de desempenho", "tipo": "Ergonômico" },
  { "agente": "Biodiesel", "tipo": "Químico" },
  { "agente": "Repetitividade de movimentos", "tipo": "Ergonômico" }
]

Possiveis Probabilidades: Não há exposição,Exposição a níveis baixos,Exposição moderada,Exposição elevada,Exposição elevadíssima 
Possiveis Efeitos: Pouca importância,Preocupantes,Severos,Irreversíveis,Ameaça
Possiveis Tipo de Exposição: Eventual/Ocasional,Habitual,Habitual/Intermitente,Habitual/Permanente,Intermitente,N.A.,Não Habitual/Não Permanente,Ocasional,Ocasional/Intermitente,Ocasional/Permanente,Permanente

Sempre responda **exatamente** neste formato Array :

  [{
      "type": "Tipo do risco (Siga o agente exato do array passado acima)",
      "name": "Agente do risco (Siga o tipo exato do agente do array passado acima)",
      "description": "Atividades e Processos",
      "fonte_geradora": "Fontes Geradora, retorne os elementos separados por vírgula, garantindo que CADA palavra comece com a primeira letra maiúscula (Exemplo: "Computador, Teclado"),
      "perigos": "Perigos",
      "probabilidade": probabilidade,
      "efeito": efeito,
      "tipo_exposicao": tipo de exposição,
      "tempo_exposicao": "Tempo de exposição ao risco,
      "epis": "EPI(s) Recomendado(s)",
      "epcs": "EPC(s) Recomendado(s)",
      "medidas_controle": "Medidas de Controle Adicional",
  }]
}

Evite variações. Não inclua explicações, apenas o Array válido.
`,
    });

    console.log(response.output_text);

    return JSON.parse(response.output_text);
  }
}

export { GetRisksService };
