import OpenAI from "openai";

interface RisksRequest {
  sector: string;
  description: string;
  occupations: string;
}

class GetRisksService {
  async execute({ sector, description, occupations }: RisksRequest) {
    if (!sector || !occupations || !description) {
      throw new Error(
        "Preencha o setor, descrição e e funções para buscar mais detalhes",
      );
    }
    const client = new OpenAI();

    const PROBABILIDADES = [
      "Não há exposição",
      "Exposição a níveis baixos",
      "Exposição moderada",
      "Exposição elevada",
      "Exposição elevadíssima",
    ];
    const EFEITOS = [
      "Pouca importância",
      "Preocupantes",
      "Severos",
      "Irreversíveis",
      "Ameaça",
    ];
    const TIPOS_EXPOSICAO = [
      "Eventual/Ocasional",
      "Habitual",
      "Habitual/Intermitente",
      "Habitual/Permanente",
      "Intermitente",
      "N.A.",
      "Não Habitual/Não Permanente",
      "Ocasional",
      "Ocasional/Intermitente",
      "Ocasional/Permanente",
      "Permanente",
    ];

    const systemInstruction = `
    Você é um assistente especialista em segurança do trabalho no Brasil. Seu objetivo é retornar informações sobre riscos ocupacionais com base no setor e nas funções fornecidas.
    
    
    LISTA OFICIAL DE AGENTES E TIPOS PERMITIDOS (Use apenas estes correspondentes):
    [
      { agente: "2,4 D + PICLORAM", tipo: "Químico" },
      { agente: "Aberturas no piso, Saliencias, Descontinuidades, obstruções ou escorregadio", tipo: "Acidentes" },
      { agente: "Acetato de butila", tipo: "Químico" },
      { agente: "Acetato de etila", tipo: "Químico" },
      { agente: "Acetileno", tipo: "Químico" },
      { agente: "Acetona", tipo: "Químico" },
      { agente: "Acidente", tipo: "Acidentes" },
      { agente: "Acidente Automobilístico", tipo: "Acidentes" },
      { agente: "Acidente com arma de fogo", tipo: "Acidentes" },
      { agente: "Acidentes - Mordidas e/ou arranhões causadas por animais domésticos.", tipo: "Acidentes" },
      { agente: "Acidentes de trânsito", tipo: "Acidentes" },
      { agente: "Acidentes Mecânicos", tipo: "Acidentes" },
      { agente: "Ácido Acético (ácido etanóico)", tipo: "Químico" },
      { agente: "Ácido benzoico", tipo: "Químico" },
      { agente: "Ácido bórico", tipo: "Químico" },
      { agente: "Ácido cítrico, Bifluoreto de amônio, Carbonato de Sódio, Nitrito de Sódio, Soda Caustica", tipo: "Químico" },
      { agente: "Ácido Linear Alquilbenzeno Sulfônico", tipo: "Químico" },
      { agente: "Ácido Nítrico", tipo: "Químico" },
      { agente: "Ácido Sulfúrico", tipo: "Químico" },
      { agente: "Adesivo plástico PVC", tipo: "Químico" },
      { agente: "Aerodispersoides (névoas, neblinas, fumos e poeiras)", tipo: "Químico" },
      { agente: "Afogamento", tipo: "Acidentes" },
      { agente: "Agentes Biológicos", tipo: "Biológico" },
      { agente: "Agressão física", tipo: "Acidentes" },
      { agente: "Água sanitária", tipo: "Químico" },
      { agente: "Álcalis Cáusticos", tipo: "Químico" },
      { agente: "Álcool 70%", tipo: "Químico" },
      { agente: "Álcool Etílico Etanol", tipo: "Químico" },
      { agente: "Alérgenos", tipo: "Químico" },
      { agente: "Ambiente de trabalho conflituoso e insatisfação coletiva", tipo: "Ergonômico" },
      { agente: "Ambiente organizacional hostil e propenso a conflitos", tipo: "Ergonômico" },
      { agente: "Amônia", tipo: "Químico" },
      { agente: "Arco elétrico em média tensão (250 V a 1.000 V)", tipo: "Acidentes" },
      { agente: "Arranjo físico inadequado", tipo: "Acidentes" },
      { agente: "Arranjo Inadequado", tipo: "Ergonômico" },
      { agente: "Assédio moral e sofrimento psíquico", tipo: "Ergonômico" },
      { agente: "Assédio Moral/Sexual", tipo: "Ergonômico" },
      { agente: "Assédio no trabalho", tipo: "Ergonômico" },
      { agente: "Ataque de animais (peçonhentos, selvagens, insetos etc.)", tipo: "Acidentes" },
      { agente: "Ataque de animais ou insetos", tipo: "Acidentes" },
      { agente: "Atingido por outros, queda de peças/estruturas/ferramentas/ferramentas, projeção de materiais (ferramentas, peças, fragmentos, fagulhas)", tipo: "Acidentes" },
      { agente: "Atividade sobre Equipamento pressurizado", tipo: "Acidentes" },
      { agente: "Atropelamento", tipo: "Acidentes" },
      { agente: "Atropelamento, Colisão", tipo: "Acidentes" },
      { agente: "Ausência de Fator de Risco", tipo: "Não Especificado" },
      { agente: "Ausência de Fator de Risco / Agente Nocivo (", tipo: "Não Especificado" },
      { agente: "Bactérias, Vírus", tipo: "Biológico" },
      { agente: "Bactérias, vírus, protozoários, fungos, príons, parasitas e outros", tipo: "Biológico" },
      { agente: "Baixa autonomia na organização do próprio trabalho", tipo: "Ergonômico" },
      { agente: "Baixa demanda no trabalho (subcarga)", tipo: "Ergonômico" },
      { agente: "Baixa justiça organizacional", tipo: "Ergonômico" },
      { agente: "Baixa umidade", tipo: "Físico" },
      { agente: "Baixa umidade do ar", tipo: "Físico" },
      { agente: "Baixo controle / Falta de autonomia", tipo: "Ergonômico" },
      { agente: "Barreiras de comunicação e agravamento de conflitos no ambiente de trabalho", tipo: "Ergonômico" },
      { agente: "Batida contra, colisão, atropelamento", tipo: "Acidentes" },
      { agente: "Batidas contra, colisões, atropelamentos", tipo: "Acidentes" },
      { agente: "Benzeno", tipo: "Químico" },
      { agente: "Biodiesel", tipo: "Químico" },
      { agente: "Butóxi etanol", tipo: "Químico" },
      { agente: "Cádmio e seus Compostos", tipo: "Químico" },
      { agente: "Cafeína", tipo: "Químico" },
      { agente: "Calor", tipo: "Físico" },
      { agente: "Calor acima LT", tipo: "Físico" },
      { agente: "CAP - Cimento Asfáltico de Petróleo - BPF - Óleo Combustível Pesado - Óleo de Xisto", tipo: "Químico" },
      { agente: "Celulose", tipo: "Químico" },
      { agente: "Choque elétrico", tipo: "Acidentes" },
      { agente: "Chumbo e seus Compostos", tipo: "Químico" },
      { agente: "Cimento e partículas suspensas", tipo: "Químico" },
      { agente: "Cimento, argamassa ou cal", tipo: "Químico" },
      { agente: "Clima Organizacional", tipo: "Ergonômico" },
      { agente: "Cloreto de Hidrogênio (Ácido Clorídrico)", tipo: "Químico" },
      { agente: "Clorexidina aquosa ou Clorexidina alcoólica", tipo: "Químico" },
      { agente: "Cloro", tipo: "Químico" },
      { agente: "Clorodifluormetano", tipo: "Químico" },
      { agente: "clorofórmio", tipo: "Químico" },
      { agente: "Cobre e seus Compostos", tipo: "Químico" },
      { agente: "Cola aderente à base de cimento vulcanizante", tipo: "Químico" },
      { agente: "Cola, cola PVC, cola adesivo de contato", tipo: "Químico" },
      { agente: "Colisão ou Abalroamento", tipo: "Acidentes" },
      { agente: "Comunicação hostil e risco de assédio moral", tipo: "Ergonômico" },
      { agente: "Comunidade Social no Trabalho", tipo: "Ergonômico" },
      { agente: "Condições Adversas", tipo: "Acidentes" },
      { agente: "Condução de veículos de qualquer natureza (Trânsito)", tipo: "Acidentes" },
      { agente: "Conflitos interpessoais", tipo: "Ergonômico" },
      { agente: "Contaminação de solos", tipo: "Químico" },
      { agente: "Contaminação de solos.", tipo: "Químico" },
      { agente: "Contato com - Partes ou móveis rotativas de Estruturas, Estruturas, Máquinas ou equipamentos", tipo: "Acidentes" },
      { agente: "Contato com líquidos ou superfícies aquecidas", tipo: "Acidentes" },
      { agente: "Contato com materiais contaminados", tipo: "Biológico" },
      { agente: "Contato com produtos cosméticos", tipo: "Químico" },
      { agente: "Contato com Superfícies Aquecidas", tipo: "Acidentes" },
      { agente: "Contato/exposição a produtos químicos", tipo: "Acidentes" },
      { agente: "Controle de Produtividade", tipo: "Ergonômico" },
      { agente: "Corante Fluorescente/Sodium C10-16 alkyl sulfate", tipo: "Químico" },
      { agente: "Corte e/ou ferimentos e/ou esmagamentos e/ou escoriações", tipo: "Acidentes" },
      { agente: "Cortes", tipo: "Acidentes" },
      { agente: "Cortes e lacerações", tipo: "Acidentes" },
      { agente: "Cortes e Perfurações", tipo: "Acidentes" },
      { agente: "Cromo e seus Compostos", tipo: "Químico" },
      { agente: "Demanda cognitiva", tipo: "Ergonômico" },
      { agente: "Demandas emocionais intensas e exposição a situações de conflito", tipo: "Ergonômico" },
      { agente: "Demandas quantitativas", tipo: "Ergonômico" },
      { agente: "Derramamento de defensivos agrícolas", tipo: "Acidentes" },
      { agente: "Descarga atmosférica", tipo: "Acidentes" },
      { agente: "Desconforto ou cansaço visual", tipo: "Ergonômico" },
      { agente: "Desconforto térmico", tipo: "Ergonômico" },
      { agente: "Desengraxante em geral", tipo: "Químico" },
      { agente: "Desengraxante em geral (Limpeza automotiva)", tipo: "Químico" },
      { agente: "Deslizamento do talude", tipo: "Acidentes" },
      { agente: "Desmotivação e perda de engajamento devido a mudanças mal geridas.", tipo: "Ergonômico" },
      { agente: "Desmotivação e queda de produtividade pela falta de reconhecimento da liderança", tipo: "Ergonômico" },
      { agente: "Desmotivação por falta de reconhecimento de ideias", tipo: "Ergonômico" },
      { agente: "Desmotivação por falta de visão dos objetivos organizacionais", tipo: "Ergonômico" },
      { agente: "Desorganização da jornada e impacto na conciliação trabalho vida pessoal.", tipo: "Ergonômico" },
      { agente: "Desrespeito e risco de conflitos interpessoais.", tipo: "Ergonômico" },
      { agente: "Detergente Enzimático", tipo: "Químico" },
      { agente: "Diesel", tipo: "Químico" },
      { agente: "Dificuldade de conciliação trabalho-vida pessoal por rigidez de jornada.", tipo: "Ergonômico" },
      { agente: "Diltiazem", tipo: "Químico" },
      { agente: "Diminuição da sua capacidade visual", tipo: "Ergonômico" },
      { agente: "dióxido de enxofre", tipo: "Químico" },
      { agente: "Doenças Infecto-contagiosas", tipo: "Biológico" },
      { agente: "Emulsão Asfáltica (Imprimer)", tipo: "Químico" },
      { agente: "Engolfamento", tipo: "Acidentes" },
      { agente: "Engolfamento ou soterramento", tipo: "Acidentes" },
      { agente: "Ensaios químicos", tipo: "Químico" },
      { agente: "Enxofre", tipo: "Químico" },
      { agente: "Equipamentos e Ferramentas", tipo: "Acidentes" },
      { agente: "Escadas e rampas inadequadas", tipo: "Acidentes" },
      { agente: "Escadas, rampas", tipo: "Acidentes" },
      { agente: "Esforço Físico", tipo: "Ergonômico" },
      { agente: "Esmagamento/ Prensamento", tipo: "Acidentes" },
      { agente: "Espaço Confinado", tipo: "Acidentes" },
      { agente: "Estireno", tipo: "Químico" },
      { agente: "Estresse ocupacional por metas inatingíveis", tipo: "Ergonômico" },
      { agente: "Etanol", tipo: "Químico" },
      { agente: "Etanol, gasolina, benzeno", tipo: "Químico" },
      { agente: "Etil benzeno", tipo: "Químico" },
      { agente: "Eventos violentos ou traumáticos", tipo: "Ergonômico" },
      { agente: "Exaustão física e mental por sobrecarga de trabalho", tipo: "Ergonômico" },
      { agente: "Exigência de alto nível de concentração, atenção e memória", tipo: "Ergonômico" },
      { agente: "Exigência de concentração e atenção", tipo: "Ergonômico" },
      { agente: "Exigência de flexões de coluna vertebral frequentes", tipo: "Ergonômico" },
      { agente: "Explosão de pneus durante enchimento", tipo: "Acidentes" },
      { agente: "Exposição a agrotóxicos", tipo: "Químico" },
      { agente: "Exposição a agrotóxicos e produtos veterinários", tipo: "Químico" },
      { agente: "Exposição a medicamentos e desinfetantes", tipo: "Químico" },
      { agente: "Exposição a Produtos Químicos", tipo: "Químico" },
      { agente: "Exposição a resíduos de defensivos agrícolas", tipo: "Químico" },
      { agente: "Exposição à Tela", tipo: "Ergonômico" },
      { agente: "Exposição a ureia automotiva e amônia", tipo: "Químico" },
      { agente: "Exposição a vapores tóxicos de defensivos agrícolas", tipo: "Químico" },
      { agente: "Fadiga e sonolência", tipo: "Ergonômico" },
      { agente: "Fadiga física e mental", tipo: "Ergonômico" },
      { agente: "Fadiga ocupacional por falta de pausas", tipo: "Ergonômico" },
      { agente: "Fadiga Visual", tipo: "Ergonômico" },
      { agente: "Falta de apoio emocional e segurança nas relações hierárquicas", tipo: "Ergonômico" },
      { agente: "Falta de Autonomia e Controle sobre o Trabalho", tipo: "Ergonômico" },
      { agente: "Falta de autonomia no trabalho para gestão de pausas", tipo: "Ergonômico" },
      { agente: "Falta de participação e sensação de imposição de mudanças.", tipo: "Ergonômico" },
      { agente: "Falta de suporte social e aumento da sensação de sobrecarga", tipo: "Ergonômico" },
      { agente: "Falta de suporte/apoio no trabalho", tipo: "Ergonômico" },
      { agente: "Fatores de Intempéries", tipo: "Acidentes" },
      { agente: "Fatores de Riscos Psicossociais", tipo: "Ergonômico" },
      { agente: "Fenol", tipo: "Químico" },
      { agente: "Ferramentas manuais", tipo: "Acidentes" },
      { agente: "Ferro", tipo: "Químico" },
      { agente: "Ferro, óxido (Fe2O3)", tipo: "Químico" },
      { agente: "Fertilizante", tipo: "Químico" },
      { agente: "Fibra de madeira para hidrossemeadura", tipo: "Químico" },
      { agente: "Fixador para hidrossemeadura", tipo: "Químico" },
      { agente: "Fluidos Refrigerantes", tipo: "Químico" },
      { agente: "Fogos de artifício - artigos de pirotecnia", tipo: "Acidentes" },
      { agente: "Formol", tipo: "Químico" },
      { agente: "Formol (Formaldeído - CH₂O)", tipo: "Químico" },
      { agente: "Fósforo e seus Compostos", tipo: "Químico" },
      { agente: "Frequente ação de puxar/empurrar cargas ou volumes", tipo: "Ergonômico" },
      { agente: "Frequente deslocamento a pé durante a jornada de trabalho", tipo: "Ergonômico" },
      { agente: "Frio", tipo: "Físico" },
      { agente: "Fumos de asfalto", tipo: "Químico" },
      { agente: "Fumos metálicos (Mn e seus compostos)", tipo: "Químico" },
      { agente: "Gás natural", tipo: "Químico" },
      { agente: "Gás R22, R410 e R32", tipo: "Químico" },
      { agente: "Gases e vapores", tipo: "Químico" },
      { agente: "Gasolina (Benzeno, Tolueno, Xileno)", tipo: "Químico" },
      { agente: "Gazes tóxicos , fumaças", tipo: "Químico" },
      { agente: "Gesso", tipo: "Químico" },
      { agente: "Glutaraldeído", tipo: "Químico" },
      { agente: "glutaraldeído.", tipo: "Químico" },
      { agente: "Graxa ou lubrificante", tipo: "Químico" },
      { agente: "Hidrocarbonetos", tipo: "Químico" },
      { agente: "Hidrocarbonetos Alifáticos(Produto desimgripante)", tipo: "Químico" },
      { agente: "Hidrocarbonetos Aromáticos", tipo: "Químico" },
      { agente: "Hidróxido de Amônia", tipo: "Químico" },
      { agente: "Hidróxido de sódio", tipo: "Químico" },
      { agente: "Hidroxizina", tipo: "Químico" },
      { agente: "Hipoclorito de sódio", tipo: "Químico" },
      { agente: "Hormônio citostático e Antibiótico", tipo: "Químico" },
      { agente: "Hormônios e Antibióticos", tipo: "Químico" },
      { agente: "Içamento de cargas", tipo: "Acidentes" },
      { agente: "Iluminação inadequada", tipo: "Ergonômico" },
      { agente: "Impacto com equipamentos", tipo: "Acidentes" },
      { agente: "Impacto contra objetos", tipo: "Acidentes" },
      { agente: "Impermeabilizantes", tipo: "Químico" },
      { agente: "Imposição de ritmos de trabalho inadequados e sensação de desvalorização", tipo: "Ergonômico" },
      { agente: "Imprudência na direção", tipo: "Acidentes" },
      { agente: "Inalação de Fumaça e Particulados", tipo: "Químico" },
      { agente: "Incêndio", tipo: "Acidentes" },
      { agente: "Incêndio/explosão", tipo: "Acidentes" },
      { agente: "Insatisfação no trabalho por falta de feedback sobre desempenho", tipo: "Ergonômico" },
      { agente: "Insatisfação no trabalho por falta de feedback sobre desempenho.", tipo: "Ergonômico" },
      { agente: "Insegurança e ansiedade devido à falta de clareza de funções", tipo: "Ergonômico" },
      { agente: "Insegurança e resistência às mudanças organizacionais", tipo: "Ergonômico" },
      { agente: "Insegurança no emprego e ausência de perspectivas de crescimento profissional", tipo: "Ergonômico" },
      { agente: "Intempéries (sol ou chuva)", tipo: "Físico" },
      { agente: "Intempéries sol ou chuva", tipo: "Acidentes" },
      { agente: "Iodo", tipo: "Químico" },
      { agente: "Isolamento e conflitos em frentes remotas", tipo: "Ergonômico" },
      { agente: "Isolamento emocional e agravamento de problemas no ambiente de trabalho.", tipo: "Ergonômico" },
      { agente: "Isolamento social e falta de suporte no ambiente de trabalho.", tipo: "Ergonômico" },
      { agente: "Jornada de trabalho prolongada", tipo: "Ergonômico" },
      { agente: "Justiça e Respeito", tipo: "Ergonômico" },
      { agente: "Levantamento, transporte manual de pesos", tipo: "Ergonômico" },
      { agente: "Lidocaína", tipo: "Químico" },
      { agente: "Limpa contato Elétrico ( hidrofluorcarbono)", tipo: "Químico" },
      { agente: "Lixos e dejetos orgânicos", tipo: "Biológico" },
      { agente: "Luminosidade", tipo: "Ergonômico" },
      { agente: "Má gestão de mudanças organizacionais", tipo: "Ergonômico" },
      { agente: "Manganês e seus compostos", tipo: "Químico" },
      { agente: "Manitol", tipo: "Químico" },
      { agente: "Manuseio de ferramentas pesadas", tipo: "Acidentes" },
      { agente: "Manuseio de materiais de limpeza em geral.", tipo: "Químico" },
      { agente: "Manuseio ou transporte de inflamáveis", tipo: "Acidentes" },
      { agente: "Máquinas e equipamentos", tipo: "Acidentes" },
      { agente: "Maquinas manuais", tipo: "Acidentes" },
      { agente: "Maquinas pesadas", tipo: "Acidentes" },
      { agente: "Maus relacionamentos no local de trabalho", tipo: "Ergonômico" },
      { agente: "Mercúrio (Hg) e seus Compostos", tipo: "Químico" },
      { agente: "Metil Etil cetona, BTX", tipo: "Químico" },
      { agente: "Microrganismos Vivos", tipo: "Biológico" },
      { agente: "Mobiliário e/ou superfícies com quinas vivas, rebarbas ou elementos de fixação expostos", tipo: "Acidentes" },
      { agente: "Mobiliário ou equipamento sem espaço para movimentação de segmentos corporais", tipo: "Ergonômico" },
      { agente: "Mobiliário sem meios de regulagem de ajuste", tipo: "Ergonômico" },
      { agente: "Monotonia", tipo: "Ergonômico" },
      { agente: "Monóxido de carbono", tipo: "Químico" },
      { agente: "Movimentos Repetitivo", tipo: "Ergonômico" },
      { agente: "Movimentos repetitivos e excesso de peso nas atividade laborais", tipo: "Ergonômico" },
      { agente: "N-Hexano", tipo: "Químico" },
      { agente: "N-hexano.", tipo: "Químico" },
      { agente: "Nafta", tipo: "Químico" },
      { agente: "Não existe (Ausencia de Fator de Risco)", tipo: "Químico" },
      { agente: "Não existente (Ausencia de Fator de Risco)", tipo: "Físico" },
      { agente: "Negro de fumo", tipo: "Químico" },
      { agente: "Nevoas e vapores de gasolina e óleo diesel", tipo: "Químico" },
      { agente: "Níquel e seus compostos tóxicos (inclui níquel carbonila e níquel tetracarbonila)", tipo: "Químico" },
      { agente: "Objeto cortantes", tipo: "Acidentes" },
      { agente: "Objetos cortantes e/ou perfurocortantes", tipo: "Acidentes" },
      { agente: "Óleo lubrificante", tipo: "Químico" },
      { agente: "Óleo Mineral", tipo: "Químico" },
      { agente: "Óleo mineral, excluídos os fluídos de trabalho com metais", tipo: "Químico" },
      { agente: "Óleo Mineral, Graxa", tipo: "Químico" },
      { agente: "Óleos e Graxas", tipo: "Químico" },
      { agente: "Ozónio", tipo: "Químico" },
      { agente: "Paracetamol", tipo: "Químico" },
      { agente: "Partes móveis", tipo: "Acidentes" },
      { agente: "Particulados", tipo: "Químico" },
      { agente: "Peróxido de metil etil cetona", tipo: "Químico" },
      { agente: "Picadas Animais Peçonhentos", tipo: "Acidentes" },
      { agente: "Piretrinas e Piretróides (inseticidas)", tipo: "Químico" },
      { agente: "Piso irregular", tipo: "Acidentes" },
      { agente: "Pisos, passagens, passarelas, escadas, plataformas, rampas, quinas vivas", tipo: "Acidentes" },
      { agente: "Pó de borracha", tipo: "Químico" },
      { agente: "Poeira Ambiente ou respirável", tipo: "Químico" },
      { agente: "Poeira de cimento", tipo: "Químico" },
      { agente: "Poeira de ferro", tipo: "Químico" },
      { agente: "Poeira PNOS - Respiráveis", tipo: "Químico" },
      { agente: "Poeira sílica", tipo: "Químico" },
      { agente: "Poeira Toxicas", tipo: "Químico" },
      { agente: "Poeira Vegetal", tipo: "Químico" },
      { agente: "Poeiras de Madeiras", tipo: "Químico" },
      { agente: "Poeiras totais/Respiráveis", tipo: "Químico" },
      { agente: "Poeiras Vapores Orgânicos - Percloroetileno", tipo: "Químico" },
      { agente: "Pólvora Negra (Carvão vegetal, Enxofre, Nitrato de potássio)", tipo: "Químico" },
      { agente: "Postura de pé por longos períodos", tipo: "Ergonômico" },
      { agente: "Postura inadequada", tipo: "Ergonômico" },
      { agente: "Postura incômoda por longos períodos", tipo: "Ergonômico" },
      { agente: "Postura sentada por longos períodos", tipo: "Ergonômico" },
      { agente: "Prensa mento e aproximação de Instalações Elétricas", tipo: "Acidentes" },
      { agente: "Prensamento do corpo ou partes do corpo", tipo: "Acidentes" },
      { agente: "Prensamento e Aproximação de Instalações Elétricas", tipo: "Acidentes" },
      { agente: "Presenteísmo", tipo: "Ergonômico" },
      { agente: "Pressão Hiperbárica", tipo: "Físico" },
      { agente: "Pressão Hipobárica", tipo: "Físico" },
      { agente: "Pressão por produtividade e risco de erros operacionais", tipo: "Ergonômico" },
      { agente: "Princípio ativo 2.4D  picloram, Tricopir ,Fluroxipir ,herbicidas, acefato, Acetamiprid", tipo: "Químico" },
      { agente: "Princípio de Incêndio", tipo: "Acidentes" },
      { agente: "Produto INTERCAP", tipo: "Químico" },
      { agente: "Produtos Biodegradáveis", tipo: "Químico" },
      { agente: "Produtos de limpeza alcalinos", tipo: "Químico" },
      { agente: "Produtos Domissanitários", tipo: "Químico" },
      { agente: "Projeção de água e objetos sob pressão", tipo: "Acidentes" },
      { agente: "Projeção de Materiais", tipo: "Acidentes" },
      { agente: "Projeção de partículas", tipo: "Acidentes" },
      { agente: "Projeção de Partículas nos Olhos", tipo: "Acidentes" },
      { agente: "Q- Herbicida, fungicidas, inseticidas", tipo: "Químico" },
      { agente: "Queda com Diferente Nível, Queda do mesmo Nível, Queda de Ferramentas, Queda de Materiais", tipo: "Acidentes" },
      { agente: "Queda de carga", tipo: "Acidentes" },
      { agente: "queda de nível e desnível", tipo: "Acidentes" },
      { agente: "Queda de objetos", tipo: "Acidentes" },
      { agente: "Queda de rocha", tipo: "Acidentes" },
      { agente: "Quedas", tipo: "Acidentes" },
      { agente: "Quedas de mesmo nível e desnível", tipo: "Acidentes" },
      { agente: "Quedas e tropeços", tipo: "Acidentes" },
      { agente: "Queimadura", tipo: "Acidentes" },
      { agente: "Querosene, Thinners", tipo: "Químico" },
      { agente: "Radiação infravermelho", tipo: "Físico" },
      { agente: "Radiação não ionizante", tipo: "Físico" },
      { agente: "Radiação não ionizante UVA UVB", tipo: "Físico" },
      { agente: "Radiação Ultravioleta", tipo: "Físico" },
      { agente: "Radiações Ionizantes", tipo: "Físico" },
      { agente: "Recompensa", tipo: "Ergonômico" },
      { agente: "Repetitividade de movimentos", tipo: "Ergonômico" },
      { agente: "Resíduos classe I inflamabilidade, corrosividade, reatividade, toxidade ou patogenicidade", tipo: "Químico" },
      { agente: "Resíduos Classe II  não-inertes ou  inertes", tipo: "Químico" },
      { agente: "Resina", tipo: "Químico" },
      { agente: "Respingos de produtos químicos", tipo: "Acidentes" },
      { agente: "Restrição da criatividade e perda de engajamento no trabalho.", tipo: "Ergonômico" },
      { agente: "Risco de desgaste emocional", tipo: "Ergonômico" },
      { agente: "Risco de desgaste emocional e desenvolvimento de transtornos mentais relacionados ao trabalho.", tipo: "Ergonômico" },
      { agente: "Risco de fadiga extrema e queda de desempenho", tipo: "Ergonômico" },
      { agente: "Risco de violência física", tipo: "Acidentes" },
      { agente: "Riscos biológicos não codificados pelo eSocial", tipo: "Biológico" },
      { agente: "Ritmo Excessivo", tipo: "Ergonômico" },
      { agente: "Ruído Contínuo ou Intermitente", tipo: "Físico" },
      { agente: "Ruído contínuo ou intermitente (Leg. Prev.)", tipo: "Físico" },
      { agente: "Ruído contínuo ou intermitente (Leg. Trabalhista)", tipo: "Físico" },
      { agente: "Sabão isolante de tubulações", tipo: "Químico" },
      { agente: "Selante para Reparos SV-01", tipo: "Químico" },
      { agente: "Sílica livre cristalizada - poeira respirável", tipo: "Químico" },
      { agente: "Silicone", tipo: "Químico" },
      { agente: "Situações de estresse", tipo: "Ergonômico" },
      { agente: "sobrecarga de Trabalho", tipo: "Ergonômico" },
      { agente: "Sobrecarga de trabalho e assédio", tipo: "Ergonômico" },
      { agente: "Sobrecarga de trabalho e conflitos de prioridade", tipo: "Ergonômico" },
      { agente: "Sobrecarga e comprometimento da produtividade", tipo: "Ergonômico" },
      { agente: "Sobrecarga física/muscular", tipo: "Ergonômico" },
      { agente: "Soda caustica , ácido clorídrico , hidróxido de amônia", tipo: "Químico" },
      { agente: "Solventes", tipo: "Químico" },
      { agente: "Stoddard solvent", tipo: "Químico" },
      { agente: "Sulfato de cálcio", tipo: "Químico" },
      { agente: "Talco - ( Mg3(Si2O5)2(OH)2 ou 3MgO.4SiO2.H2O )", tipo: "Químico" },
      { agente: "Tetracaína/Lidocaína", tipo: "Químico" },
      { agente: "Tintas, esmaltes, vernizes e outras variados", tipo: "Químico" },
      { agente: "Tolueno", tipo: "Químico" },
      { agente: "Tolueno e Xileno, Etanol", tipo: "Químico" },
      { agente: "Tombamento de máquinas ou equipamentos", tipo: "Acidentes" },
      { agente: "Tombamento e Colisão", tipo: "Acidentes" },
      { agente: "Trabalho a quente", tipo: "Acidentes" },
      { agente: "Trabalho com animais infectados", tipo: "Biológico" },
      { agente: "Trabalho diurno ou  noturno", tipo: "Ergonômico" },
      { agente: "Trabalho em altura (maior que 2 metros)", tipo: "Acidentes" },
      { agente: "Trabalho em altura - 1,80 m", tipo: "Acidentes" },
      { agente: "Trabalho em ambientes com risco de queda do mesmo nível/ Nível diferente", tipo: "Acidentes" },
      { agente: "Trabalho em condições de difícil comunicação", tipo: "Ergonômico" },
      { agente: "Transporte de produtos inflamáveis", tipo: "Acidentes" },
      { agente: "Umidade", tipo: "Físico" },
      { agente: "Urotropina", tipo: "Químico" },
      { agente: "Uso frequente de alavancas e pedais", tipo: "Ergonômico" },
      { agente: "Uso frequente de pedais e alavancas", tipo: "Ergonômico" },
      { agente: "Vapores", tipo: "Químico" },
      { agente: "Vapores orgânicos", tipo: "Químico" },
      { agente: "Veículos pesados", tipo: "Acidentes" },
      { agente: "Verniz, solvente, tinta outros derivados", tipo: "Químico" },
      { agente: "Vibração de corpo inteiro", tipo: "Físico" },
      { agente: "Vibrações de corpo inteiro - (AREN e VDVR)", tipo: "Físico" },
      { agente: "Vibrações de Mãos e Braços- AREN", tipo: "Físico" },
      { agente: "Vírus e Bactérias", tipo: "Biológico" },
      { agente: "Xileno", tipo: "Químico" },
      { agente: "Zinco", tipo: "Químico" }
    ]
  `;

    const response = await client.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: systemInstruction,
        },
        {
          role: "user",
          content: `Retorne os riscos para o setor ${sector}. ${description ? `Descrição do ambiente do setor: ${description}.` : ""} Funções de trabalho envolvidas: ${occupations}.`,
        },
      ],
      response_format: {
        type: "json_schema",
        json_schema: {
          name: "riscos_ocupacionais",
          strict: true,
          schema: {
            type: "object",
            properties: {
              riscos: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    tipo: {
                      type: "string",
                      description:
                        "Tipo do risco correspondente ao tipo exato do agente.",
                    },
                    name: {
                      type: "string",
                      description: "Agente do risco exato da lista fornecida.",
                    },
                    description: {
                      type: "string",
                      description: "Atividades e Processos detalhados.",
                    },
                    fonte_geradora: {
                      type: "string",
                      description:
                        "Elementos separados por vírgula com iniciais maiúsculas.",
                    },
                    perigos: { type: "string" },
                    probabilidade: { type: "string", enum: PROBABILIDADES },
                    efeito: { type: "string", enum: EFEITOS },
                    tipo_exposicao: { type: "string", enum: TIPOS_EXPOSICAO },
                    tempo_exposicao: {
                      type: "string",
                      description: "Tempo de exposição estimado.",
                    },
                    epis: {
                      type: "string",
                      description: "EPI(s) Recomendado(s)",
                    },
                    epcs: {
                      type: "string",
                      description: "EPC(s) Recomendado(s)",
                    },
                    medidas_controle: {
                      type: "string",
                      description: "Medidas de Controle Adicional",
                    },
                  },
                  required: [
                    "tipo",
                    "name",
                    "description",
                    "fonte_geradora",
                    "perigos",
                    "probabilidade",
                    "efeito",
                    "tipo_exposicao",
                    "tempo_exposicao",
                    "epis",
                    "epcs",
                    "medidas_controle",
                  ],
                  additionalProperties: false,
                },
              },
            },
            required: ["riscos"],
            additionalProperties: false,
          },
        },
      },
      temperature: 0.1,
    });

    const jsonValido = JSON.parse(response.choices[0].message.content || "{}");
    jsonValido.riscos?.map((data) => {
      data.type = data.tipo;
    });
    return jsonValido.riscos;
  }
}

export { GetRisksService };
